inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 6.0
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "ember/**/*"
    - "doc"
