version: '3.9'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677

  webdriver_chrome:
    image: selenium/standalone-chrome-debug
    environment:
      START_XVFB: '${USE_XVFB}'
    shm_size: '2g'
    ports:
      - 4444:4444
      - 5900:5900

  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
      USE_XVFB: '${USE_XVFB}'
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./doc:/doc
    environment:
      SWAGGER_JSON: /doc/openapi.yml
