version: '3.9'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql

  webdriver_chrome:
    image: selenium/standalone-chrome
    environment:
      START_XVFB: 'false'
    ports:
      - 4444:4444

  rails:
    build: .
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
