name: RSpec

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports: ["3306:3306"]
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: nanasess/setup-chromedriver@master

    - name: Setup Rails
      env:
        RAILS_ENV: test
      run: |
        gem install bundler --no-document --no-ri
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        cp config/.ci.database.yml config/database.yml
        bin/rails db:setup
        yarn

    - name: Run RSpec
      env:
        RAILS_ENV: test
        TZ: Asia/Tokyo
        CI: true
        DISPLAY: ':99'
      run: |
        bundle exec rspec
