name: ember-ci

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: cd ember/todo-app && yarn install --frozen-lockfile
      - name: Lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: cd ember/todo-app && yarn lint
