name: ReviewDog

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: rubocop
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: gemfile
        rubocop_flags: -a
        rubocop_extensions: rubocop-rails:gemfile
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: true

    - name: Notify slack build result
      uses: lazy-actions/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: '*ReviewDog*'
          mention: 'here'
          username: 'GitHub Actions'
          icon_emoji: 'dog'
          mention_if: 'failure'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
