name: ReviewDog

on:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: rubocop
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: gemfile
        rubocop_flags: -a
        rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        fail_on_error: true

    - name: Notify slack build result
      uses: lazy-actions/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: '*ReviewDog Rubocop*'
          mention: 'here'
          username: 'GitHub Actions'
          icon_emoji: 'dog'
          mention_if: 'failure'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

  brakeman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
    - name: brakeman
      uses: reviewdog/action-brakeman@v2
      with:
        brakeman_version: gemfile
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
    - name: Notify slack build result
      uses: lazy-actions/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: '*ReviewDog Brakeman*'
          mention: 'here'
          username: 'GitHub Actions'
          icon_emoji: 'dog'
          mention_if: 'failure'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: install ember-cli
      run: yarn global add ember-cli

    - name: Setup Ember.js App and eslint formatter
      env:
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        cd ember/todo-app
        yarn
        yarn add eslint-formatter-rdjson -D

    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        cd ember/todo-app
        yarn --silent run eslint -f rdjson . | reviewdog -f=rdjson -reporter=github-pr-review

    - name: Notify slack build result
      uses: lazy-actions/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: '*ReviewDog eslint*'
          mention: 'here'
          username: 'GitHub Actions'
          icon_emoji: 'dog'
          mention_if: 'failure'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
